Fy no warnings
SETI/pds-cspyce pull request #133
Opened 2023-08-08 20:17 UTC by fyellin

Eliminate warnings when compiling the extensions.  This means that we can use the warnings for what they were intended for: catching mistyped arguments.

For now, we're punting on the automatically generated vector methods, and surrounding the places where there might be problems with "pragma".  Maybe fix this in the future.

2023-08-09 23:04 UTC, rfrenchseti requested changes

2023-08-09 23:04 UTC, rfrenchseti commented on swig/cspyce0.i
> +        frmchg_(&frame1, &frame2, &et, (SpiceDouble *)xform);   // CHECK THIS!
Should this be checked before approving?

2023-08-09 23:53 UTC, fyellin commented
Well, this is embarrassing.

The thing I forgot to double check turns out to be okay.  That fourth
argument really is a double* float, and that's what I wanted to verify.
But. . . .

It turns out that the argument is actually a double[6][6], and that it's
directly calling Fortran.  And remember the bug I just filed against
SpiceyPy where it ends with up a transposed array because it directly calls
Fortran. Yup. We're doing the same thing.

So. . . .   I'm going to
1. Remove this comment for now, since the thing I was supposed to check is
correct.
2. File a bug mentioning this bug and that we need to investigate all
direct calls to Fortran functions
3. Fix it.

And. . . .

Back at Google, if you wrote "DO NOT SUBMIT" in your code, then the code
manager would not let you push it.  A good way of not making stupid
mistakes like this one.

On Wed, Aug 9, 2023 at 4:04 PM Robert French ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In swig/cspyce0.i
> <https://github.com/SETI/pds-cspyce/pull/133#discussion_r1289339261>:
>
> > @@ -3308,7 +3289,7 @@ extern void frinfo_c(
>          SpiceDouble et,
>          SpiceDouble xform[6][6])
>      {
> -        frmchg_(&frame1, &frame2, &et, xform);
> +        frmchg_(&frame1, &frame2, &et, (SpiceDouble *)xform);   // CHECK THIS!
>
> Should this be checked before approving?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SETI/pds-cspyce/pull/133#pullrequestreview-1570746510>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABC2LIK5SK27T7DIPPYKYC3XUQJQRANCNFSM6AAAAAA3I7PFL4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-10 02:29 UTC, rfrenchseti approved these changes

2023-08-10 02:29 UTC, merged