Don't use one version of spice across all builds.
SETI/pds-cspyce pull request #5
Opened 2022-03-28 20:47 UTC by fyellin

Modify build process so that we don't rely on a pre-downloaded version of cspice.  Each use of setup.py will download the sources from NAIF if they are not already available.

2022-03-28 22:03 UTC, rfrenchseti requested changes

2022-03-28 23:42 UTC, fyellin commented on get_spice.py
> +# module cspyce.cspyce1
Done

2022-03-28 23:43 UTC, fyellin commented on get_spice.py
> +# This module is responsible for downloading the cspice source codes based on whatever
Changed to "files".

2022-03-28 23:45 UTC, fyellin commented
All comments handled. 

I merged SETI/pds-cspyce into fyellin/pds-cspyce, so I have no idea why github things this pull request is so many changes.  I

2022-03-29 00:37 UTC, rfrenchseti approved these changes

2022-03-29 00:38 UTC, merged