Issue 42.  Partial fix, pending decision by Rob/Mark/Emilie
SETI/pds-cspyce pull request #55
Opened 2023-05-20 16:11 UTC by fyellin

Fix typemap. Add test.

2023-05-20 22:33 UTC, rfrenchseti commented
All tests are failing. I've asked Emilie to make the kernel loader support all the kernels so we don't have to worry about this problem in the future. However, since she is still working on `test_d.py`, it would be better if you put new test routines in a different (new) file so that she doesn't have to deal with the merge conflicts. Then we can merge those files in by hand (or delete them if they are just copies of what's eventually going to be in `test_d.py`).

2023-05-21 05:30 UTC, fyellin commented
Pulled tests, as requested.  All tests pass.

2023-05-21 14:30 UTC, rfrenchseti requested changes
You need to remove your changes to the workflows.

2023-05-22 01:03 UTC, rfrenchseti approved these changes

2023-05-22 01:51 UTC, merged