Merge in Mark's stuff
SETI/pds-cspyce pull request #6
Opened 2022-04-11 23:50 UTC by fyellin

Mark has added more cspyce functions.  He also automated the generation of the cspyce0_info.py files from the .i files.  

This is his changes, with some slight cleanup by me

2022-04-13 19:12 UTC, rfrenchseti requested changes
There is an empty file called "2". Is this supposed to be there?

2022-04-13 19:12 UTC, rfrenchseti commented on cspyce/cspyce1.py
> +    func.ABSTRACT  = CSPYCE_ABSTRACT[name]
Duplicate line?

2022-04-14 21:56 UTC, fyellin commented on cspyce/cspyce1.py
> +# The cspyce0 module contains Python interfaces to all CSPICE functions likely
Fixed

2022-04-14 22:02 UTC, fyellin commented on cspyce/cspyce1.py
> +# cspyce1, all CSPYCE runtime errors raise Python exceptions. You should never
Mark's comment.  But I agree with you

2022-04-14 22:07 UTC, fyellin commented on cspyce/cspyce1.py
> +    func.ABSTRACT  = CSPYCE_ABSTRACT[name]
Fixed

2022-04-14 22:09 UTC, fyellin commented
I think I made all changes this time.

2022-04-14 22:21 UTC, merged