Turn some C-structures into Python records
SETI/pds-cspyce pull request #82
Opened 2023-06-08 02:17 UTC by fyellin

Turn SpiceDLADescr and SpiceDSKDescr into numpy records rather than opaque arrays.
Leave Plane and Ellipse as numpy arrays, but make them into special values understood by the typemap.  This lessens the chances of errors.

Added ability to debug (barely) the generated C code.

2023-06-08 02:18 UTC, fyellin commented
CLOSES #81

2023-06-08 02:28 UTC, fyellin commented
Note to Emilia:

I deleted the line `dskdsc = np.rec.array(dskdsc, dtype=DSK_DESCRIPTOR_TYPE)[0]` from test_d.c`.  This is no longer necessary, and actually no longer works.  I see that you added several tests to 17-cspyce_unit_test that included this line.  They, also need to be deleted.

2023-06-09 00:26 UTC, fyellin commented
This is ready for review. . . .

2023-06-09 17:51 UTC, rfrenchseti requested changes
This does not close issue #81. See Mark's comment on that issue about adding functions to apply record types to ellipses and planes.

2023-06-09 17:51 UTC, rfrenchseti commented on cspyce/record_support.py
> +    """ Creates a new empty record whose descriptor has the indicated name. """
Remove extra spaces before/after """

2023-06-09 17:51 UTC, rfrenchseti commented on swig/cspyce_typemaps.i
> +* These typemaps are for data-structures in which the user wants to see a a record
"a a"

2023-06-09 19:57 UTC, fyellin commented
Mark's comments are taken into account.  SpiceDSKDescr and SpiceDLADescr
are actual numpy records with named fields.  SpicePlane and SpiceEllipse
are treated as normal numpy arrays.  However we refer to them as
SpicePlane* and SpiceEllipse* in typemaps and function prototypes to
improve type safety.  Also Plane's and Ellipse's can only be INPUT or
OUTPUT, again for type safety.

Typos fixed soon.


On Fri, Jun 9, 2023 at 10:51 AM Robert French ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> This does not close issue #81
> <https://github.com/SETI/pds-cspyce/issues/81>. See Mark's comment on
> that issue about adding functions to apply record types to ellipses and
> planes.
> ------------------------------
>
> In cspyce/record_support.py
> <https://github.com/SETI/pds-cspyce/pull/82#discussion_r1224588951>:
>
> > +        ('frmcde', np.int32),
> +        ('corsys', np.int32),
> +        ('corpar', np.double, 10),
> +        ('co1min', np.double),
> +        ('co1max', np.double),
> +        ('co2min', np.double),
> +        ('co2max', np.double),
> +        ('co3min', np.double),
> +        ('co3max', np.double),
> +        ('start',  np.double),
> +        ('stop',   np.double)])
> +}
> +
> +
> +def create_record(name):
> +    """ Creates a new empty record whose descriptor has the indicated name. """
>
> Remove extra spaces before/after """
> ------------------------------
>
> In swig/cspyce_typemaps.i
> <https://github.com/SETI/pds-cspyce/pull/82#discussion_r1224591607>:
>
> > @@ -3169,6 +3177,143 @@ TYPEMAP_OUT(SpiceChar)
>
>  #undef TYPEMAP_OUT
>
> +/*******************************************************************************
> +* Typemaps for records.
> +*
> +* These typemaps are for data-structures in which the user wants to see a a record
>
> "a a"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SETI/pds-cspyce/pull/82#pullrequestreview-1472780726>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABC2LIJUEY45E4RFYE5I3L3XKNPDPANCNFSM6AAAAAAY6USVPY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-09 20:06 UTC, fyellin commented on cspyce/record_support.py
> +    """ Creates a new empty record whose descriptor has the indicated name. """
Done

2023-06-09 20:06 UTC, fyellin commented on swig/cspyce_typemaps.i
> +* These typemaps are for data-structures in which the user wants to see a a record
Done

2023-06-09 20:35 UTC, fyellin commented
I will merge in the other changes, too.

2023-06-09 20:54 UTC, fyellin commented
Okay.  I just reread Mark's comments and I see he added something that seems interesting.  Let me handle that as a separate pull request.  There's an idea I want to try out.

2023-06-09 22:19 UTC, rfrenchseti approved these changes

2023-06-09 22:19 UTC, merged